### ISSUE TITLE
Multiple taxa (genus/species) annotated as separate taxonomicNames

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#50] opened 2019-10-31 11:22 UTC
In: `ejt-550_johansson_cederberg`

See screenshot. I have not encountered such a case before so I decided to bring it to your attention

![scrn18](https://user-images.githubusercontent.com/22291049/67942826-68719b80-fbe1-11e9-9e0a-cc087e29b425.png)

**Comment by gsautter** [comment] 2019-10-31 15:40
Thanks for this. There are multiple tickets in this regard in a few other trackers already, so I'm well aware of this problem. In particular, this is an issue with the in-memory representation of the documents that gets in the way of annotation nesting assessment. Saving and reloading the document fixes it, so this is very hard to reproduce and investigate, which is why I couldn't fix it yet.

As to repairing this, "Tools -> Check Annotation Nesting" cleans it up.

**Comment by gsautter** [comment] 2019-10-31 15:41
Closing this issue because there are already a good few others for the same problem.

**Closed as completed by gsautter** 2019-10-31 15:41 UTC
Labels: invalid

**Comment by brokentool** [comment] 2019-11-01 07:57
> As to repairing this, "Tools -> Check Annotation Nesting" cleans it up.

perfect!
