### ISSUE TITLE
Ghost errors

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#41] opened 2019-09-24 12:44 UTC
In: `zootaxa.4638.3.8`

Currently only Critical error in this document. Could not find the cause. Checked paragraph regions and XML view.

**Comment by gsautter** [comment] 2019-09-24 15:55
I cannot seem to find any critical errors in this document ... fixed a few "Figure/Table never cited", but that's about it. Are you sure the document name is correct?

**Comment by brokentool** [comment] 2019-09-25 09:31
Yes, I am. I have a suspicion that sometimes resolved errors remain in the list of the currently opened document, but then disappear once the document is closed. It occurred to me several times in similar circumstances.

**Comment by gsautter** [comment] 2019-09-25 12:26
If even "Re-Check All" doesn't change that, there is something hinky about this ... but I'll need to at least reproduce one case to be able to investigate.

**Comment by brokentool** [comment] 2019-09-26 12:36
- changed title of issue
- changed category to `bug`

I think I found an example. In: `zootaxa.4655.1.1`

See screenshot. There are two Critical errors for Text Streams. Re-Check removes them, but then after resolving broken geo-coordinates elsewhere in the document, the two errors returned. Even though they are in the list, there are no unmerged paragraphs where the errors point to.

![scrn13](https://user-images.githubusercontent.com/22291049/65688209-5eed9480-e073-11e9-9e7b-452bdb968a3f.png)

**Comment by gsautter** [comment] 2019-09-26 14:11
Now this is truly weird ... there is no indication of a paragraph break after this parenthesis at all (the right and bottom edges would be thickened on that word, as would be the left and top ones of the subsequent word). Does the XML view reveal anything? I cannot seem to reproduce any of this behavior, not the coming back of errors, either ...

**Comment by brokentool** [comment] 2019-09-27 05:33
XML view showed paragraphs correctly, no breaks or anything I could determine. When I closed the document, after submitting here, it still showed the two crits as present, in the list of documents.

**Comment by angel-s-slavchev** [comment] 2019-09-27 12:51
zootaxa.4671.2.11
Here is s small file where the system insists the meterial citation is broken, even though no text is annotated as such.

(a couple of screenshots)
![2671 1 11 01](https://user-images.githubusercontent.com/44800901/65770398-b0168a80-e13e-11e9-8006-0897fdf1512f.png)
![2671 2 11 02](https://user-images.githubusercontent.com/44800901/65770401-b1e04e00-e13e-11e9-8324-1db4dacea6da.png)

**Comment by gsautter** [comment] 2019-09-27 12:59
Freaky ... I just opened that last document, did a "Re-Check All", and the materials citation errors were gone instantly ... hard to tell how they got in there in the first place.

Sometimes, it might help to save and close, a document and re-open it if something like this happens. Still up to me how these things can emerge at all in the first place, but closing and re-opening might help.

**Comment by angel-s-slavchev** [comment] 2019-09-27 13:00
Will keep in mind as a general solution for such cases. I usually go through re-checking, but don't usually close and re-open.

**Comment by brokentool** [comment] 2019-11-06 15:03
Don't know why this was closed, as it keeps happening.

Case in point: `zootaxa.4675.1.1`

See screenshot, list shows 90 Criticals, when I open the document, there are none to be found. Re-Check does not show them or any others. Upon closing the document, there are Ø errors in the list.

![scrn21](https://user-images.githubusercontent.com/22291049/68309578-5008f180-00b7-11ea-86b1-a17cbd37c1a3.png)

**Comment by gsautter** [comment] 2019-11-06 15:15
Do these 90 criticals prevail when you reload the document _list_? That would be good to know, as if not, it is merely a local update problem, but if they prevail, there is a server side functionality problem.

**Comment by brokentool** [comment] 2019-11-06 15:18
not sure about this doc, but I can confidently say that it did happen at least twice with two others, upon reloading the list on the next day

**Comment by gsautter** [comment] 2019-11-06 15:25
OK, that's pretty weird ... I'll check the logs if there are any errors regarding updates to the document error table (which happens when the error protocol is updated in an IMF on server side).

To speed up matters, do you have a (rough) recollection of when you first fixed the errors that reappeared the next day?

**Comment by brokentool** [comment] 2019-12-03 09:17
Here is another example: `zootaxa.4675.1.1`. Showed up with errors in the list. When I opened it, it did not have any Crits or Blockers. Re-checked, still no errors. Closed documents, shows no error in the list.

**Comment by angel-s-slavchev** [comment] 2019-12-03 14:25
Also `zootaxa.4682.1.1`
Same as above - multiple Blockers and Criticals in the list, no suck erors when I open it; no re-checks change this.

**Comment by gsautter** [comment] 2019-12-03 16:20
Thanks for this, guys, found it in the sever log. There is some error happening when updating the database table that contributes the numbers to the QC Tool document list, which is most likely the reason you see outdated numbers ... investigating ...

**Comment by gsautter** [comment] 2019-12-03 17:44
Got it ... somehow, some line breaks appear to have gotten into the descriptions of a few errors, and since the error protocols use a line based, tab separated data format, this pretty much breaks up records in two. I've now put measures in place to prevent such cases from the source now ... currently working on a repair script for the broken protocols.

**Comment by gsautter** [comment] 2019-12-03 18:41
A small analysis script shows that we have a total of 85 lines in 44 error protocol files with such line break errors, belonging to 20 IMFs. Moving on to actual repair now ...

**Comment by gsautter** [comment] 2019-12-03 19:34
All repaired now, and the error statistics table providing the numbers to the QC Tool document list is updated as well, so there should be no more Ghost errors.

**Closed as completed by gsautter** 2019-12-03 19:34 UTC
Labels: bug
