### ISSUE TITLE
Acarologia journal paragraph breaks

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#88] opened 2020-06-15 13:48 UTC
QC-ing the Acarologia journal, I noted that 80% of new lines start a paragraph in all articles.

I believe there is something wrong with the OCR of this particular journal, because I have never seen so many of this type of error in a particular journal up to now

This also messes up the references, since if they are longer than a single line of text, they are either not tagged to the end, or are tagged as more than one reference, when it is just one

![Untitled](https://user-images.githubusercontent.com/22291049/84664758-ac72a000-af27-11ea-8ece-c9342a4cf89a.png)

**Comment by Carol-Sokolowicz** [comment] 2020-06-15 14:01
Hi, @brokentool 
 Felipe asked me to answer this for him.
 He believes the problem is a template issue related to the Minimum Block Margin.
But he'll check it out and get back to you.
Cheers

**Comment by flsimoes** [comment] 2020-06-15 15:24
@brokentool 

I checked this particular UUID and the other ones from Acarologia, and this seems to be a one-off. I made some adjustments to it.

**Comment by gsautter** [comment] 2020-06-15 19:06
Which exact document is this? A UUID or name would surely help me take a look ... I do remember there is one journal whose main text has a lot of space on its left (which messes with statistical block structuring because every line looks indented), with figures, tables, and captions protruding into this extremely wide left page margin, along with page headers ... is it that one?

**Comment by flsimoes** [comment] 2020-06-15 19:10
Here you go @gsautter 1F25FFC6FF90FFDD4038FFBE173A5A4E

Earlier I partly fixed this (there are still some wrong paragraphs down there, also, check the captions out).

Had to slightly tweak the template as well because the header area extended just a bit more to the right than I predicted.

**Comment by flsimoes** [comment] 2020-06-15 19:11
A couple of UUIDs that **did not** have the same problems:

FFCC4345FFA2034D7554FF85FFF53F4C
DE581E105000FFC6FF81FFD6F440FF81

**Comment by gsautter** [comment] 2020-06-15 19:13
> Here you go @gsautter 1F25FFC6FF90FFDD4038FFBE173A5A4E

@flsimoes tahnks, I'll take a look soon as you're done with that document ...

**Comment by flsimoes** [comment] 2020-06-15 19:13
Forgot to close it, sorry!

**Comment by gsautter** [comment] 2020-06-15 19:16
No problem ... `FFCC4345FFA2034D7554FF85FFF53F4C` already answered my question ... it _is_ this one with the wide left page margin and the protruding page footers, captions, and illustrations ... need to think up a solution for this one, most likely shrinking the columns around the main text blocks.

**Comment by flsimoes** [comment] 2020-06-15 19:19
Indeed, those protruding parts do mess up the whole thing.

**Comment by gsautter** [comment] 2020-06-15 19:34
What you can do is remove the `column` regions and then use "Revise Block Paragraphs", as the latter measures against the main text blocks if there is no `column` region surrounding a block ... just as a shortcut measure for more convenient fixing.

**Comment by gsautter** [comment] 2020-06-15 19:36
I could also add a template parameter "Shrink Columns to Main Text" to get the columns reduced to the right dimensions ... or do you have other ideas?

**Comment by flsimoes** [comment] 2020-06-15 19:37
I like the idea, but how would it affect the captions (They seem to not always follow the main text rule/lining)?

**Comment by gsautter** [comment] 2020-06-15 19:40
That shrinking would have to happen after the captions are marked ... or in several rounds before _and_ after marking the captions ... not saying it's straightforward ... maybe discarding the columns might be better ... not sure, need to think this through ...

**Comment by brokentool** [comment] 2020-06-16 13:47
> 
> 
> @brokentool
> 
> I checked this particular UUID and the other ones from Acarologia, and this seems to be a one-off. I made some adjustments to it.

I went through about 5 articles in this journal and they all had this issue, IIRC.

there are very few articles from this journal in the list, and for 5 of them my name stands as "last updated by". unfortunately, I had already fixed the text stream errors before I posted here, which, upon reflection, was a mistake.

incidentally, how do I get the UUID for an article, so that I can be more precise when giving examples?

**Comment by flsimoes** [comment] 2020-06-16 14:06
Well, now that is weird. When I ran these as test batches here they all looked fine (otherwise I would have not uploaded them).

I'll run them again locally to see if I can replicate the error.

Regarding UUIDs, how do you access the publications normally? Here we use the UUIDs solely, so I guess you must access it through other means. Basically the UUID is the last part of the html address (numbers + all-caps letters).

**Comment by flsimoes** [comment] 2020-06-16 14:23
@brokentool I had a look again and indeed the errors keep happening. Not sure how/why I missed these.

Anyway, you won't be seeing other papers from this journal for the time being as we are focusing on others (hopefully less complicated).

Thanks for letting me know.

**Comment by brokentool** [comment] 2020-06-16 14:29
> Regarding UUIDs, how do you access the publications normally?

using the QC tool (started from the console), I load the list of articles with errors and jump in =]

**Comment by flsimoes** [comment] 2020-06-16 14:34
By the way, what's the command line for the QC tool? (we use it only through the graphic version)

**Comment by brokentool** [comment] 2020-06-17 05:55
OK, here's the full protocol: I run `GgImagine.exe` to get any updates, then close it. then I open a console in the folder where GgImagine is installed, and run

`java -jar GgImagineQcTool.jar HOST=https://tb.plazi.org/GgServer/proxy AUTH=***********`

where the asterisks are my authorization password

**Comment by gsautter** [comment] 2020-06-17 12:41
Syntax for the `AUTH` parameter is `<user>:<password>`.

**Comment by flsimoes** [comment] 2020-06-17 12:55
Thanks @brokentool 

@gsautter I was looking more into running it locally, but I always get this error after running the tool in a folder:
[GgImagineQcTool.20200617-0940.err.log](https://github.com/gsautter/goldengate-qualitycontrol/files/4792580/GgImagineQcTool.20200617-0940.err.log)

Perhaps I'm missing something, maybe even in the Batch Processing stage (is there a parameter that specifically saves a QC log file?).

**Comment by gsautter** [comment] 2020-06-17 16:47
@flsimoes the QC tool basically complains that it doesn't find any IMFs with _separate_ error protocols next to them (in ZIPs names `<imfName>.ep.zip` in the same folder). Looking through the IMFs proper would mean to potentially unzip several gigabytes worth of IMFs just to check for error protocols, which would be way too slow.
These separate error protocols are exported by a dedicated gizmo at the end of the batch. However, said gizmo currently is _not_ part of `Default.imagine`, simply because we didn't need it so far ... I'll include it with the next update.

**Comment by flsimoes** [comment] 2020-06-17 16:50
Thanks! I knew about said gizmo, was just under the impression that it had been implemented. Sorry about the confusion.

**Comment by gsautter** [comment] 2020-06-17 16:53
> Thanks! I knew about said gizmo, was just under the impression that it had been implemented. Sorry about the confusion.

Oh, it _is_ implemented, just not packed into `Default.imagine` right now ... removed it at some point because it was of no use to our workflow at the time ... just have to re-add it in the next update.

**Comment by gsautter** [comment] 2020-07-02 02:21
Re-added the error protocol exporter in the update published on the weekend. Let me know if there are any problems.

**Closed as completed by gsautter** 2020-07-02 02:21 UTC
Labels: bug
